-- ==========================================================
-- V1__initial_schema.sql
-- Initial database schema for JobShield Core Entities
-- ==========================================================

-- 1. Users Table
CREATE TABLE IF NOT EXISTS users (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    phone_number VARCHAR(50),
    role VARCHAR(50) NOT NULL DEFAULT 'USER',
    account_status VARCHAR(50) DEFAULT 'ACTIVE',
    email_verified BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 2. Scam Campaign Table (Base)
CREATE TABLE IF NOT EXISTS scam_campaign (
    campaign_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    campaign_code VARCHAR(50) NOT NULL UNIQUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 3. Job Analysis Table (Base)
CREATE TABLE IF NOT EXISTS job_analysis (
    analysis_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    company_name VARCHAR(100) NOT NULL,
    job_title VARCHAR(100) NOT NULL,
    salary VARCHAR(50),
    job_description TEXT NOT NULL,
    risk_score INT,
    risk_level VARCHAR(20),
    ai_reason TEXT,
    scam_pattern VARCHAR(100),
    campaign_id BIGINT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_analysis_user FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE,
    CONSTRAINT fk_analysis_campaign FOREIGN KEY (campaign_id) REFERENCES scam_campaign(campaign_id) ON DELETE SET NULL
);

-- 4. Saved Jobs Table
CREATE TABLE IF NOT EXISTS saved_jobs (
    save_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    analysis_id BIGINT NOT NULL,
    notes TEXT,
    saved_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_user_analysis UNIQUE (user_id, analysis_id),
    CONSTRAINT fk_saved_user FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE,
    CONSTRAINT fk_saved_analysis FOREIGN KEY (analysis_id) REFERENCES job_analysis(analysis_id) ON DELETE CASCADE
);
